### ISSUE TITLE
Organization pulldown on "Propose Change of Library Entry" dialog ends at letter M

### ISSUE THREAD

**Issue by larsborn** [malpedia/feedback#46] opened 2023-05-10 18:09 UTC
**Describe the bug**
On the "Propose Change of Library Entry" dialog, the pulldown for the Organization (optional) doesn't show all existing entries. There is, for example an entry "Netlab" but currently the pulldown ends with "Medium ...".

**To Reproduce**
1. Go to https://malpedia.caad.fkie.fraunhofer.de/library?search=360netlab
2. Click on the "suggest change" icon for any entry
3. Open pulldown for Organization
4. You cannot select "Netlab"

**Expected behavior**
I know that the entry "Netlab" should exist, because there are articles from it: https://malpedia.caad.fkie.fraunhofer.de/library?search=Netlab

**Desktop:**
 - OS: Windows
 - Browser Brave

**Comment by danielplohmann** [comment] 2023-05-11 08:19
Hey Lars, 
thanks for the feedback!

Oh oh, looks like we are in for debugging a specific combination for this one.
Here is Firefox on Ubuntu.
![image](https://github.com/malpedia/feedback/assets/9798598/da07ace3-7295-4198-aaa4-9907ff20fcfb)

I just tested on a Win10 as well and get similar results for Firefox and Chrome.
So I was not able to reproduce this issue yet but I will try Brave from a Windows VM soon.

**Comment by steffenenders** [comment] 2023-05-11 08:39
I was able to reproduce the issue and will take a closer look at it later.

**Comment by steffenenders** [comment] 2023-05-11 13:26
@larsborn Should be fixed! Thanks again for letting us know :)

**Closed as completed by steffenenders** 2023-05-11 13:26 UTC
Labels: bug

**Comment by larsborn** [comment] 2023-05-11 13:49
Awesome, thanks a lot for the quick turnaround!! ❤️
